table Orders
	lineageTag: 9d84dae2-ce29-45d9-8850-4e4065e873f9

	measure 'Total Sales' = SUM(Orders[Sales])
		lineageTag: 715e3879-4392-4143-92d7-43ec1e08ca60

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = SUM(Orders[Profit])
		lineageTag: e6f3bdfd-e2a0-4e3b-a1bc-570f84d9f85c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Orders' = DISTINCTCOUNT(Orders[Order ID])
		formatString: 0
		lineageTag: aa041c4b-7c0f-46d1-81c9-7342569eb75b

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 1a6c3b5c-e205-49cb-aa0a-053366141311
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 66888697-e82e-466c-a9e9-e10d2d268c71
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: b3736efa-a241-4f76-aad6-8bd13fa20d6b
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: ed2b0ee3-90f2-4b00-9016-de510561fc7c
			defaultHierarchy: LocalDateTable_54a08b99-b01a-46a4-8a04-344e0e782537.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: a939b06f-5f79-4a4a-ad8d-250b87c9decd
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 69096e28-b809-4caf-a6f9-5b7d0b48c052
			defaultHierarchy: LocalDateTable_1448a670-4a11-43f6-bad8-5d5647bd686d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: e92aeaef-ee44-4c8f-996a-28bef2a8f46b
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 9b827795-23e4-4b1d-8e66-58a5db297516
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: ae0b9e45-561a-4626-b963-b465c747d392
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: bf87eacb-704a-481e-9b53-30dedaf4c68c
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: 43b183ec-fc4e-4e70-8d91-809ba7020b3e
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 45af7b3d-58c7-4823-ae90-a96486f1303d
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State/Province
		dataType: string
		lineageTag: d872ac83-9c50-4252-8fdd-d98bcca6c85c
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: ddb82329-47ac-4236-897e-46287c03ea13
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 3377e172-eb90-4e52-92fa-f697cd5b8e10
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: c148c1c9-25ca-481b-9027-1f4ce6f87662
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 3931b81c-18e4-436a-b5ef-4dda298f5580
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 7ea1a844-2835-434b-9b95-94dd01bd56b5
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 0c60f835-c6b4-4093-bdb5-b05b586dfb7c
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 2708bdc1-dfb0-4082-82a9-25cb8afc9726
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 5c769081-cf7b-4e96-81e7-39f9e7b454fc
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: a8e520ed-e8f4-4890-a76a-c20129b700ee
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 106328bf-32c6-4587-9800-60d862ff8696
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Docker\Downloads\sample_superstore.xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

